# Generated by Django 5.2.3 on 2025-07-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='anonymous_id',
            field=models.CharField(blank=True, help_text='A unique anonymous ID for the user.', max_length=100, null=True, unique=True),
        ),
    ]
